// export { ReactComponent as checkmark } from './checkmark.svg';
// export { ReactComponent as dropZone } from './dragZone.svg';
// export { ReactComponent as firstPlaceDragon } from './firstPlaceDragon.svg';
// export { ReactComponent as readMe } from './readMe.svg';
// export { ReactComponent as secondPlaceDragon } from './secondPlaceDragon.svg';
// export { ReactComponent as thirdPlaceDragon } from './thirdPlaceDragon.svg';
export { default as checkmark } from './checkmark.svg';
export { default as dropZone } from './dragZone.svg';
export { default as firstPlaceDragon } from './firstPlaceDragon.svg';
export { default as readMe } from './readMe.svg';
export { default as secondPlaceDragon } from './secondPlaceDragon.svg';
export { default as thirdPlaceDragon } from './thirdPlaceDragon.svg';
